import type { Game } from "@/lib/types";
import { expandedSeedGames } from "@/lib/expanded-game-data";

const originalLicense = {
  type: "original" as const,
  proofUrl: "/about#content-rights",
  rightsExpiresAt: null,
};

const coreSeedGames: Omit<Game, "id">[] = [
  {
    slug: "neon-kestrel-drift",
    title: "Neon Kestrel Drift",
    tagline: "Thread impossible corners, charge your boost, and chase the cleanest line through a city that never slows down.",
    description:
      "A compact arcade racer about clean corners, close calls, and building a flawless neon run. This playable JoyCircuit demo uses entirely original code and visual assets.",
    instructions:
      "Use the arrow keys or WASD to steer. Avoid traffic, collect energy gates, and survive as long as you can. Press P to pause.",
    developer: { name: "JoyCircuit Studio", website: null },
    embedUrl: "/games/neon-kestrel-drift/index.html",
    thumbnailUrl: "/api/game-art/neon-kestrel-drift?variant=thumbnail",
    coverUrl: "/api/game-art/neon-kestrel-drift?variant=cover",
    aspectRatio: "16 / 9",
    orientation: "landscape",
    inputModes: ["keyboard"],
    multiplayerMode: "solo",
    ageRating: "Everyone",
    status: "new",
    featuredRank: 1,
    license: originalLicense,
    publishedAt: "2026-07-18T08:00:00.000Z",
    categories: ["racing", "arcade"],
    tags: ["fast", "endless", "high-score"],
    accent: "#59F0B2",
  },
  {
    slug: "moonbug-rally",
    title: "Moonbug Rally",
    tagline: "Low gravity, high stakes, one wonderfully bouncy rover.",
    description:
      "Race a nimble moon buggy across crater fields where every jump changes your route. Time boosts carefully and keep all four wheels pointed home.",
    instructions: "Accelerate with W or Up, brake with S or Down, and balance in the air with A and D.",
    developer: { name: "Crater Cartworks", website: null },
    embedUrl: "/games/joy-arcade/index.html?game=moonbug-rally",
    thumbnailUrl: "/api/game-art/moonbug-rally?variant=thumbnail",
    coverUrl: "/api/game-art/moonbug-rally?variant=cover",
    aspectRatio: "16 / 9",
    orientation: "landscape",
    inputModes: ["keyboard", "gamepad"],
    multiplayerMode: "solo",
    ageRating: "Everyone",
    status: "published",
    featuredRank: 6,
    license: originalLicense,
    publishedAt: "2026-07-12T08:00:00.000Z",
    categories: ["racing", "arcade"],
    tags: ["space", "physics", "rally"],
    accent: "#8B7CFF",
  },
  {
    slug: "tumbletower-trials",
    title: "Tumbletower Trials",
    tagline: "Climb a cheerful tower where absolutely nothing stays still.",
    description:
      "A physics arcade challenge filled with wobbling bridges, springy blocks, and silly shortcuts. Reach the bell before the tower rearranges itself.",
    instructions: "Move with WASD or the arrow keys. Press Space to jump and hold it for a higher bounce.",
    developer: { name: "Odd Angle Games", website: null },
    embedUrl: "/games/joy-arcade/index.html?game=tumbletower-trials",
    thumbnailUrl: "/api/game-art/tumbletower-trials?variant=thumbnail",
    coverUrl: "/api/game-art/tumbletower-trials?variant=cover",
    aspectRatio: "4 / 3",
    orientation: "landscape",
    inputModes: ["keyboard", "gamepad"],
    multiplayerMode: "solo",
    ageRating: "Everyone",
    status: "published",
    featuredRank: 7,
    license: originalLicense,
    publishedAt: "2026-07-08T08:00:00.000Z",
    categories: ["arcade", "platformer"],
    tags: ["physics", "climbing", "colorful"],
    accent: "#FFB65C",
  },
  {
    slug: "astro-alley-strikers",
    title: "Astro Alley Strikers",
    tagline: "Street football takes a zero-gravity detour.",
    description:
      "Bank shots off orbiting bumpers and work with your crew in a quick-fire space sport built for friendly rivalries.",
    instructions: "Move with WASD, aim with the mouse, and click to pass or shoot. Hold click to add power.",
    developer: { name: "Orbit Local", website: null },
    embedUrl: "/games/joy-arcade/index.html?game=astro-alley-strikers",
    thumbnailUrl: "/api/game-art/astro-alley-strikers?variant=thumbnail",
    coverUrl: "/api/game-art/astro-alley-strikers?variant=cover",
    aspectRatio: "16 / 9",
    orientation: "landscape",
    inputModes: ["keyboard", "mouse", "gamepad"],
    multiplayerMode: "online-multiplayer",
    ageRating: "Everyone",
    status: "published",
    featuredRank: 4,
    license: originalLicense,
    publishedAt: "2026-07-15T08:00:00.000Z",
    categories: ["sports", "multiplayer"],
    tags: ["football", "team", "space"],
    accent: "#52D9FF",
  },
  {
    slug: "pebble-pop-lab",
    title: "Pebble Pop Lab",
    tagline: "Tiny stones, satisfying chains, surprisingly big experiments.",
    description:
      "A tactile color-matching puzzle where each pop can trigger a clever laboratory chain reaction. This playable demo is an original JoyCircuit production.",
    instructions: "Click or tap groups of two or more matching pebbles. Clear the target colors before you run out of moves.",
    developer: { name: "JoyCircuit Studio", website: null },
    embedUrl: "/games/pebble-pop-lab/index.html",
    thumbnailUrl: "/api/game-art/pebble-pop-lab?variant=thumbnail",
    coverUrl: "/api/game-art/pebble-pop-lab?variant=cover",
    aspectRatio: "4 / 3",
    orientation: "landscape",
    inputModes: ["mouse", "touch"],
    multiplayerMode: "solo",
    ageRating: "Everyone",
    status: "new",
    featuredRank: 2,
    license: originalLicense,
    publishedAt: "2026-07-20T08:00:00.000Z",
    categories: ["puzzle", "cozy"],
    tags: ["match", "relaxing", "high-score"],
    accent: "#FF6B9E",
  },
  {
    slug: "hex-garden",
    title: "Hex Garden",
    tagline: "Grow a pocket-sized world, one thoughtful tile at a time.",
    description:
      "Place garden tiles to connect streams, flowers, and shady groves. There is no timer—just a small landscape waiting to fit together.",
    instructions: "Select a tile, rotate it with R or a second tap, then place it beside matching garden edges.",
    developer: { name: "Soft Moss Assembly", website: null },
    embedUrl: "/games/joy-arcade/index.html?game=hex-garden",
    thumbnailUrl: "/api/game-art/hex-garden?variant=thumbnail",
    coverUrl: "/api/game-art/hex-garden?variant=cover",
    aspectRatio: "4 / 3",
    orientation: "landscape",
    inputModes: ["mouse", "touch"],
    multiplayerMode: "solo",
    ageRating: "Everyone",
    status: "published",
    featuredRank: 8,
    license: originalLicense,
    publishedAt: "2026-06-29T08:00:00.000Z",
    categories: ["cozy", "puzzle", "strategy"],
    tags: ["tiles", "nature", "no-timer"],
    accent: "#8DEB81",
  },
  {
    slug: "skyhook-sprint",
    title: "Skyhook Sprint",
    tagline: "Swing above the clouds and make every second count.",
    description:
      "A momentum platformer about chaining grapples between floating beacons. This playable JoyCircuit demo is made with original code, shapes, and sound-free effects.",
    instructions: "Use A and D or the arrow keys to move. Press Space to jump and click or press X to fire the skyhook.",
    developer: { name: "JoyCircuit Studio", website: null },
    embedUrl: "/games/skyhook-sprint/index.html",
    thumbnailUrl: "/api/game-art/skyhook-sprint?variant=thumbnail",
    coverUrl: "/api/game-art/skyhook-sprint?variant=cover",
    aspectRatio: "16 / 9",
    orientation: "landscape",
    inputModes: ["keyboard", "mouse"],
    multiplayerMode: "solo",
    ageRating: "Everyone",
    status: "new",
    featuredRank: 3,
    license: originalLicense,
    publishedAt: "2026-07-19T08:00:00.000Z",
    categories: ["platformer", "action"],
    tags: ["grappling", "speedrun", "clouds"],
    accent: "#52D9FF",
  },
  {
    slug: "tiny-titan-tactics",
    title: "Tiny Titan Tactics",
    tagline: "Pocket-sized heroes. Properly enormous decisions.",
    description:
      "Guide a band of miniature titans across compact turn-based encounters where positioning matters more than raw power.",
    instructions: "Select a titan, choose a highlighted tile, then pick an action. End your turn when the squad is ready.",
    developer: { name: "Lantern Table", website: null },
    embedUrl: "/games/joy-arcade/index.html?game=tiny-titan-tactics",
    thumbnailUrl: "/api/game-art/tiny-titan-tactics?variant=thumbnail",
    coverUrl: "/api/game-art/tiny-titan-tactics?variant=cover",
    aspectRatio: "16 / 9",
    orientation: "landscape",
    inputModes: ["mouse", "touch"],
    multiplayerMode: "solo",
    ageRating: "Everyone 10+",
    status: "published",
    featuredRank: 9,
    license: originalLicense,
    publishedAt: "2026-07-02T08:00:00.000Z",
    categories: ["strategy", "adventure"],
    tags: ["turn-based", "heroes", "tactical"],
    accent: "#F7D45C",
  },
  {
    slug: "marshmallow-mech",
    title: "Marshmallow Mech",
    tagline: "A soft hero lands the hardest punches.",
    description:
      "Pilot a squishy experimental mech through a toy-box city, bouncing hazards back at mischievous clockwork invaders.",
    instructions: "Move with WASD, aim with the mouse, click to punch, and press Shift to bounce-dash.",
    developer: { name: "Sugarbolt Works", website: null },
    embedUrl: "/games/joy-arcade/index.html?game=marshmallow-mech",
    thumbnailUrl: "/api/game-art/marshmallow-mech?variant=thumbnail",
    coverUrl: "/api/game-art/marshmallow-mech?variant=cover",
    aspectRatio: "16 / 9",
    orientation: "landscape",
    inputModes: ["keyboard", "mouse", "gamepad"],
    multiplayerMode: "solo",
    ageRating: "Everyone 10+",
    status: "published",
    featuredRank: 5,
    license: originalLicense,
    publishedAt: "2026-07-16T08:00:00.000Z",
    categories: ["action", "arcade"],
    tags: ["mech", "brawler", "bouncy"],
    accent: "#FF8CB7",
  },
  {
    slug: "vault-of-vines",
    title: "Vault of Vines",
    tagline: "Every overgrown doorway is hiding a better question.",
    description:
      "Explore a living ruin, redirect sunlight, and coax ancient plants into bridges as you uncover the vault's quiet history.",
    instructions: "Move with the arrow keys, interact with E, and drag mirrors with the mouse to redirect beams of light.",
    developer: { name: "Green Key Studio", website: null },
    embedUrl: "/games/joy-arcade/index.html?game=vault-of-vines",
    thumbnailUrl: "/api/game-art/vault-of-vines?variant=thumbnail",
    coverUrl: "/api/game-art/vault-of-vines?variant=cover",
    aspectRatio: "16 / 9",
    orientation: "landscape",
    inputModes: ["keyboard", "mouse"],
    multiplayerMode: "solo",
    ageRating: "Everyone",
    status: "published",
    featuredRank: 10,
    license: originalLicense,
    publishedAt: "2026-06-21T08:00:00.000Z",
    categories: ["adventure", "puzzle"],
    tags: ["exploration", "nature", "story"],
    accent: "#62D895",
  },
  {
    slug: "comet-kitchen",
    title: "Comet Kitchen",
    tagline: "Dinner is at eight. The asteroid arrives at seven fifty-nine.",
    description:
      "Coordinate a tiny orbital kitchen, pass ingredients between stations, and keep the soup inside the bowl when gravity flips.",
    instructions: "Move with WASD. Press E to pick up or pass ingredients and Space to use the nearest kitchen station.",
    developer: { name: "Second Serving Games", website: null },
    embedUrl: "/games/joy-arcade/index.html?game=comet-kitchen",
    thumbnailUrl: "/api/game-art/comet-kitchen?variant=thumbnail",
    coverUrl: "/api/game-art/comet-kitchen?variant=cover",
    aspectRatio: "16 / 9",
    orientation: "landscape",
    inputModes: ["keyboard", "gamepad"],
    multiplayerMode: "local-coop",
    ageRating: "Everyone",
    status: "published",
    featuredRank: 11,
    license: originalLicense,
    publishedAt: "2026-07-10T08:00:00.000Z",
    categories: ["multiplayer", "arcade"],
    tags: ["cooking", "co-op", "space"],
    accent: "#FF8F5C",
  },
  {
    slug: "shadowboard",
    title: "Shadowboard",
    tagline: "Skate the line between the city and its silhouette.",
    description:
      "Flip between a moonlit rooftop and its paper-cut shadow to reveal rails, ramps, and hidden paths through the night.",
    instructions: "Use the arrow keys to ride, Space to jump, and Q to switch between the real city and its shadow.",
    developer: { name: "Night Paper Co.", website: null },
    embedUrl: "/games/joy-arcade/index.html?game=shadowboard",
    thumbnailUrl: "/api/game-art/shadowboard?variant=thumbnail",
    coverUrl: "/api/game-art/shadowboard?variant=cover",
    aspectRatio: "16 / 9",
    orientation: "landscape",
    inputModes: ["keyboard", "gamepad"],
    multiplayerMode: "solo",
    ageRating: "Everyone 10+",
    status: "published",
    featuredRank: 12,
    license: originalLicense,
    publishedAt: "2026-06-14T08:00:00.000Z",
    categories: ["adventure", "platformer"],
    tags: ["skating", "stylized", "exploration"],
    accent: "#8B7CFF",
  },
];

const combinedSeedGames = [...coreSeedGames, ...expandedSeedGames];
const uniqueSeedSlugs = new Set(combinedSeedGames.map((game) => game.slug));
if (uniqueSeedSlugs.size !== combinedSeedGames.length) {
  throw new Error("JoyCircuit seed data contains duplicate game slugs.");
}

export const seedGames: Omit<Game, "id">[] = combinedSeedGames;
